### ISSUE TITLE
integration with Substance Painter does not work

### ISSUE THREAD

**Issue by coralhl** [Digiography/blender_addon_pipeline#1]
because there must be
`Popen([bpy.context.user_preferences.addons[__package__].preferences.option_sp_exe])`
instead of
https://github.com/Digiography/blender_addon_pipeline/blob/fab4abc5076fa4376bc38a75b3c693e2c018f084/ds_sp.py#L15

But even after this change, Substance Painter opens with an empty window.

It will also be nice to have the option to export selected objects in the fbx instead of the whole scene.

**Comment by Digiography** [comment]
I've just uploaded 0.9.0 which fixes the Substance Painter issue and I've added an option to export selected mesh to OBJ.  A SPP project file now gets created and a textures folder is set for export.
